server:
  port: 8085

spring:
  application:
    name: settlement-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow?currentSchema=settlement
    username: payflow
    password: payflow_secret
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: settlement
  flyway:
    enabled: true
    schemas: settlement
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
